### ISSUE TITLE
Unstoppable scrolling/loading and inevitable lockup after X time

### ISSUE THREAD

**Issue by MostHated** [mike-ward/Loon#3]
Hey there,
    I was testing this out on Linux (Pop_OS 21.04) and noticed at first that if I scrolled down roughly 3-4 pages (if the height of the app is max size at a standard resolution), the app seems to YOLO and just starts scrolling non-stop loading as much as it can and in doing so, locking up the app, only to occasionally unlock for a fraction of a second to try and load everything on screen that it had been loading while the interface was locked up. It quickly went from about 250mb of memory usage to 1gb, then kept going up before I was forced to kill the process. 

I then reopened it to see if just letting it sit on screen would help without scrolling, but after a relatively short amount of time (1-2 minutes or so), I scrolled down one single tick and it began to do the same thing again.

Any attempts to stop it other than killing the process, such as right-clicking to try and force it to scroll back to the top, were in vain. 
That said, its a great idea and I really like it. Though, I will like it more if I can use it longer than 30 seconds, lol.

Thanks,
-MH

**Comment by mike-ward** [comment]
See:
- https://github.com/AvaloniaUI/Avalonia.Controls.ItemsRepeater/issues/3
- https://github.com/AvaloniaUI/Avalonia.Controls.ItemsRepeater/issues/4

It is worse on Linux, less so on Windows. The Avalonia team is stretched thin and it may be some time before they address this.
